### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by kalemas** [MKlimenko/aTools_python3#6]
Hi, there seem to be install issue

![IMG_20240510_155140_772](https://github.com/MKlimenko/aTools_python3/assets/638393/c5ae59fc-c206-4dfc-a6dc-1f28573fb576)

Here

https://github.com/MKlimenko/aTools_python3/blob/b82f11a88dd96de533bfa795b50fae772a084742/aTools_install.mel#L103

**Comment by MKlimenko** [comment]
Hi @kalemas,

I checked the link to the archive and it's working. Potentially, this might be happening if you're working from behind a proxy.

**Comment by kalemas** [comment]
Network communication may throw many types of errors, packet loss, network adapter interoperability, server refusal.

Error printing and breaking script execution in error handler should help to manage such cases. World I do a PR?

**Comment by MKlimenko** [comment]
This repo is purely a port of the original aTools from python2 to python3 without any modifications. Due to the lack of CI, I intend to keep it that way and not introduce any changes.

Since the link itself is working, it has something to do with your environment. Feel free to publish your findings here for future reference.

**Comment by MKlimenko** [comment]
Closed due to inactivity, feel free to reopen.
